### ISSUE TITLE
Unable to login after registering the user.

### ISSUE THREAD

**Issue by haseebmirza** [amoschihi/Laravel-ERP#1]
LoginController.php
<?php

namespace App\Http\Controllers\Auth;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\AuthenticatesUsers;

class LoginController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Login Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles authenticating users for the application and
    | redirecting them to your home screen. The controller uses a trait
    | to conveniently provide its functionality to your applications.
    |
    */

    use AuthenticatesUsers;

    /**
     * Where to redirect users after login.
     *
     * @var string
     */
    protected $redirectTo = 'home';

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('guest')->except('logout');
    }

    /**
     * Get the needed authorization credentials from the request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    protected function credentials(Request $request)
    {
        return [
            'email'=>$request->{$this->username()},
            'password'=>$request->password,
            'status'=>1

        ];
    }
}

**Comment by amoschihi** [comment]
Hello @haseebmirza, i didn't quite get the exact error you are having...

**Comment by haseebmirza** [comment]
When i register student user below link. assign role in db user_roles table.
Laravel-ERP-master/public/register
After registering, it automatically login and show student dashboard(home).
When i click logout. next time unable to login. It redirects to same login page, when i input credentials and press "Login Button".

Failed to load resource: the server responded with a status of 404 (Not Found)
montserrat-v10-latin-regular.ttf:1

console is showing this error.

I hope you understand the problem.

**Comment by amoschihi** [comment]
> When i register student user below link. assign role in db user_roles table.
> Laravel-ERP-master/public/register
> After registering, it automatically login and show student dashboard(home).
> When i click logout. next time unable to login. It redirects to same login page, when i input credentials and press "Login Button".
> 
> Failed to load resource: the server responded with a status of 404 (Not Found)
> montserrat-v10-latin-regular.ttf:1
> 
> console is showing this error.
> 
> I hope you understand the problem.

Yeah I understand.../login route is only for students and there is a middleware that checks that. Logging out from student portal should redirect you to '/'. Also note that /admin/login route middleware redirects based on roles thus no role for student dashboard. You are unable to login because of middleware restrictions. You can fix that by customizing the middlewares (Found at App\Http\Middlewares) to work the way you want.
