### ISSUE TITLE
Credentials not working.

### ISSUE THREAD

**Issue by vignesh-subash** [amoschihi/Laravel-ERP#4]
Given login credentials is not working when Importing 

> lincoln.sql

**Comment by amoschihi** [comment]
@vignesh-subash you can modify credentials directly using bcrypt encryption. Let me know if you have any problem. Thanks

**Comment by vignesh-subash** [comment]
Hi, Thanks for the quick reply. i tried adding new password in db itself but its not login and also not showing any error also.

**Comment by vignesh-subash** [comment]
i imported your lincoln sql files to the db only.

**Comment by amoschihi** [comment]
Is the password you added to db encrypted?
Also check this;
route - admin/login uses admins table, and /login - uses users table. Which one is not showing error?

**Comment by amoschihi** [comment]
/admin/login - username is (code doctor) 
                          with space and password is  
                          lincoln for admin with role               
                          instructor.
                         - For Super admin, username       
                          is amos and password is     
                          lincoln

/login - use amos as username and lincoln 
              as password

**Comment by vignesh-subash** [comment]
Encrypted Password only used. Earlier itself i tried with above mentioned password only. again replaced the sql file again.
routes also used admin/user tables respectively.
while trying to login its not either login or not showing any error also. It just redirect again to login page.
In users table, there is field verify token column is generated in default and its empty only.

**Comment by anditiohua123** [comment]
Fucking idiot.. testing your code idiot.. your sql and your coding is not working
